# .goreleaser.yaml
version: 2
project_name: flow

before:
  hooks:
    - go mod tidy

builds:
  - id: flow
    main: ./
    binary: flow
    env: [CGO_ENABLED=0]
    flags: [-trimpath]
    ldflags:
      - -s -w
      - -X github.com/selimacerbas/flow/cmd.version={{.Version}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - id: binaries
    formats: [binary]  # <- was `format: binary` (deprecated)
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'  # no .exe here

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto
