name: release
on:
  push:
    tags:
      - 'v*'  # e.g., v0.1.0

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go from go.mod
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.FUNCTION_PATH }}/${{ matrix.function }}/go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
